import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

interface InvoiceData {
  invoiceNumber: string;
  date: string;
  customerName: string;
  items: {
    description: string;
    quantity: number;
    unitPrice: number;
    total: number;
  }[];
  subtotal: number;
  tax?: number;
  total: number;
}

interface ReportData {
  title: string;
  dateRange: string;
  summary: { label: string; value: string }[];
  tableData?: { headers: string[]; rows: string[][] };
}

export function generateInvoicePDF(data: InvoiceData): void {
  const doc = new jsPDF();

  // Header
  doc.setFillColor(14, 165, 233); // Primary blue color
  doc.rect(0, 0, 210, 40, "F");

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(28);
  doc.setFont("helvetica", "bold");
  doc.text("INVOICE", 20, 28);

  doc.setFontSize(12);
  doc.setFont("helvetica", "normal");
  doc.text(`#${data.invoiceNumber}`, 180, 28, { align: "right" });

  // Company Info
  doc.setTextColor(30, 41, 59);
  doc.setFontSize(10);
  doc.text("BizManager", 20, 55);
  doc.setTextColor(100, 116, 139);
  doc.text("Your Business Management Solution", 20, 62);

  // Invoice Details
  doc.setTextColor(30, 41, 59);
  doc.setFontSize(10);
  doc.setFont("helvetica", "bold");
  doc.text("Invoice Date:", 140, 55);
  doc.text("Bill To:", 20, 80);

  doc.setFont("helvetica", "normal");
  doc.text(data.date, 180, 55, { align: "right" });
  doc.setTextColor(71, 85, 105);
  doc.text(data.customerName || "Walk-in Customer", 20, 88);

  // Items Table
  const tableStartY = 100;
  autoTable(doc, {
    startY: tableStartY,
    head: [["Description", "Qty", "Unit Price", "Total"]],
    body: data.items.map((item) => [
      item.description,
      item.quantity.toString(),
      `$${item.unitPrice.toFixed(2)}`,
      `$${item.total.toFixed(2)}`,
    ]),
    headStyles: {
      fillColor: [14, 165, 233],
      textColor: [255, 255, 255],
      fontStyle: "bold",
      fontSize: 10,
    },
    bodyStyles: {
      textColor: [30, 41, 59],
      fontSize: 10,
    },
    alternateRowStyles: {
      fillColor: [248, 250, 252],
    },
    columnStyles: {
      0: { cellWidth: 80 },
      1: { cellWidth: 30, halign: "center" },
      2: { cellWidth: 40, halign: "right" },
      3: { cellWidth: 40, halign: "right" },
    },
    margin: { left: 20, right: 20 },
  });

  // Get the final Y position after the table
  const finalY = (doc as any).lastAutoTable.finalY + 10;

  // Totals Section
  doc.setDrawColor(226, 232, 240);
  doc.line(120, finalY, 190, finalY);

  doc.setTextColor(71, 85, 105);
  doc.setFont("helvetica", "normal");
  doc.text("Subtotal:", 130, finalY + 10);
  doc.text(`$${data.subtotal.toFixed(2)}`, 190, finalY + 10, { align: "right" });

  if (data.tax) {
    doc.text("Tax:", 130, finalY + 20);
    doc.text(`$${data.tax.toFixed(2)}`, 190, finalY + 20, { align: "right" });
  }

  doc.setDrawColor(226, 232, 240);
  doc.line(120, finalY + 25, 190, finalY + 25);

  doc.setTextColor(30, 41, 59);
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text("Total:", 130, finalY + 35);
  doc.text(`$${data.total.toFixed(2)}`, 190, finalY + 35, { align: "right" });

  // Footer
  doc.setTextColor(148, 163, 184);
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.text("Thank you for your business!", 105, 270, { align: "center" });
  doc.text("Generated by BizManager", 105, 278, { align: "center" });

  doc.save(`invoice-${data.invoiceNumber}.pdf`);
}

export function generateReportPDF(data: ReportData): void {
  const doc = new jsPDF();

  // Header
  doc.setFillColor(14, 165, 233);
  doc.rect(0, 0, 210, 45, "F");

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(24);
  doc.setFont("helvetica", "bold");
  doc.text(data.title, 20, 25);

  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");
  doc.text(data.dateRange, 20, 35);
  doc.text(`Generated: ${new Date().toLocaleDateString()}`, 190, 35, { align: "right" });

  // Summary Section
  let yPos = 60;
  doc.setTextColor(30, 41, 59);
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text("Summary", 20, yPos);
  yPos += 10;

  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");

  data.summary.forEach((item) => {
    doc.setTextColor(71, 85, 105);
    doc.text(item.label, 20, yPos);
    doc.setTextColor(30, 41, 59);
    doc.setFont("helvetica", "bold");
    doc.text(item.value, 100, yPos);
    doc.setFont("helvetica", "normal");
    yPos += 8;
  });

  // Table Data if provided
  if (data.tableData && data.tableData.rows.length > 0) {
    yPos += 10;
    autoTable(doc, {
      startY: yPos,
      head: [data.tableData.headers],
      body: data.tableData.rows,
      headStyles: {
        fillColor: [14, 165, 233],
        textColor: [255, 255, 255],
        fontStyle: "bold",
        fontSize: 10,
      },
      bodyStyles: {
        textColor: [30, 41, 59],
        fontSize: 9,
      },
      alternateRowStyles: {
        fillColor: [248, 250, 252],
      },
      margin: { left: 20, right: 20 },
    });
  }

  // Footer
  doc.setTextColor(148, 163, 184);
  doc.setFontSize(9);
  doc.text("Generated by BizManager", 105, 285, { align: "center" });

  const fileName = data.title.toLowerCase().replace(/\s+/g, "-");
  doc.save(`${fileName}-report.pdf`);
}

export function generateProfitLossReportPDF(
  totalRevenue: number,
  totalCost: number,
  totalExpenses: number,
  grossProfit: number,
  netProfit: number,
  expensesByCategory: { name: string; value: number }[],
  dateRange: string
): void {
  const doc = new jsPDF();

  // Header
  doc.setFillColor(14, 165, 233);
  doc.rect(0, 0, 210, 45, "F");

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(24);
  doc.setFont("helvetica", "bold");
  doc.text("Profit & Loss Report", 20, 25);

  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");
  doc.text(dateRange, 20, 35);
  doc.text(`Generated: ${new Date().toLocaleDateString()}`, 190, 35, { align: "right" });

  // Format currency helper
  const formatCurrency = (amount: number) => {
    return new Intl.NumberFormat("en-US", {
      style: "currency",
      currency: "USD",
    }).format(amount);
  };

  // Profit & Loss Statement
  let yPos = 60;
  doc.setTextColor(30, 41, 59);
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text("Profit & Loss Statement", 20, yPos);
  yPos += 15;

  // Revenue Section
  doc.setFillColor(34, 197, 94);
  doc.rect(20, yPos - 5, 170, 12, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(11);
  doc.text("Revenue", 25, yPos + 3);
  doc.text(formatCurrency(totalRevenue), 185, yPos + 3, { align: "right" });
  yPos += 20;

  // Cost Section
  doc.setFillColor(14, 165, 233);
  doc.rect(20, yPos - 5, 170, 12, "F");
  doc.setTextColor(255, 255, 255);
  doc.text("Less: Cost of Goods Sold", 25, yPos + 3);
  doc.text(`(${formatCurrency(totalCost)})`, 185, yPos + 3, { align: "right" });
  yPos += 20;

  // Gross Profit
  doc.setFillColor(248, 250, 252);
  doc.rect(20, yPos - 5, 170, 12, "F");
  doc.setTextColor(30, 41, 59);
  doc.setFont("helvetica", "bold");
  doc.text("Gross Profit", 25, yPos + 3);
  doc.setTextColor(grossProfit >= 0 ? 34 : 239, grossProfit >= 0 ? 197 : 68, grossProfit >= 0 ? 94 : 68);
  doc.text(formatCurrency(grossProfit), 185, yPos + 3, { align: "right" });
  yPos += 20;

  // Expenses Section
  doc.setFillColor(234, 179, 8);
  doc.rect(20, yPos - 5, 170, 12, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "normal");
  doc.text("Less: Operating Expenses", 25, yPos + 3);
  doc.text(`(${formatCurrency(totalExpenses)})`, 185, yPos + 3, { align: "right" });
  yPos += 20;

  // Net Profit
  doc.setFillColor(netProfit >= 0 ? 34 : 239, netProfit >= 0 ? 197 : 68, netProfit >= 0 ? 94 : 68);
  doc.rect(20, yPos - 5, 170, 14, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.text("Net Profit / (Loss)", 25, yPos + 4);
  doc.text(formatCurrency(netProfit), 185, yPos + 4, { align: "right" });
  yPos += 30;

  // Expenses Breakdown
  if (expensesByCategory.length > 0) {
    doc.setTextColor(30, 41, 59);
    doc.setFontSize(14);
    doc.text("Expenses Breakdown", 20, yPos);
    yPos += 10;

    autoTable(doc, {
      startY: yPos,
      head: [["Category", "Amount", "% of Total"]],
      body: expensesByCategory.map((exp) => [
        exp.name,
        formatCurrency(exp.value),
        totalExpenses > 0 ? `${((exp.value / totalExpenses) * 100).toFixed(1)}%` : "0%",
      ]),
      headStyles: {
        fillColor: [14, 165, 233],
        textColor: [255, 255, 255],
        fontStyle: "bold",
        fontSize: 10,
      },
      bodyStyles: {
        textColor: [30, 41, 59],
        fontSize: 10,
      },
      alternateRowStyles: {
        fillColor: [248, 250, 252],
      },
      columnStyles: {
        0: { cellWidth: 80 },
        1: { cellWidth: 50, halign: "right" },
        2: { cellWidth: 40, halign: "right" },
      },
      margin: { left: 20, right: 20 },
    });
  }

  // Footer
  doc.setTextColor(148, 163, 184);
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.text("Generated by BizManager", 105, 285, { align: "center" });

  doc.save(`profit-loss-report-${new Date().toISOString().split("T")[0]}.pdf`);
}
